### ISSUE TITLE
Error: Error fetching account

### ISSUE THREAD

**Issue by dustinromey** [kevinschaich/mintable#109]
**Steps to Reproduce:**

1. Install mintable
2. link Plaid account as per instructions
3. Link one bank account
4. run mintable fetch

I've tried this with two different accounts, same result each time.

**Error:**

```
2020-10-08T13:39:24.573Z [ERROR] Error fetching account XYZ.

 { TypeError: Cannot read property 'join' of null
    at /home/user/.local/bin/npm/lib/node_modules/mintable/lib/integrations/plaid/plaidIntegration.js:303:60
    at Array.map (<anonymous>)
    at /home/user/.local/bin/npm/lib/node_modules/mintable/lib/integrations/plaid/plaidIntegration.js:294:62
    at process._tickCallback (internal/process/next_tick.js:68:7)
  [stack]:
   'TypeError: Cannot read property \'join\' of null\n    at /home/user/.local/bin/npm/lib/node_modules/mintable/lib/integrations/plaid/plaidIntegration.js:303:60\n    at Array.map (<anonymous>)\n    at /home/user/.local/bin/npm/lib/node_modules/mintable/lib/integrations/plaid/plaidIntegration.js:294:62\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
  [message]: 'Cannot read property \'join\' of null' } 

```

**System Info:**

```
arch: x64
platform: linux
os: v5.4.0-7642-generic
mintable: v2.0.1
node: v10.19.0
```

**Comment by gbdavidx** [comment]
how do you get the code verification at the end? no page opens for me

**Comment by kevinschaich** [comment]
Hey @dustinromey folks were having similar issues on `node 10.x.x` in https://github.com/kevinschaich/mintable/issues/108. Could you try upgrading to `>=11.0.0` and see if that fixes your issue?

**Comment by kevinschaich** [comment]
Hey all closing this one since no responses for the last few months. Please open a new issue if you need help.
