### ISSUE TITLE
Finally got it installed but getting a warning with centos

### ISSUE THREAD

**Issue by gbdavidx** [kevinschaich/mintable#115]
INFO] Fetched 3 sub-accounts and 84 transactions.
(node:8977) UnhandledPromiseRejectionWarning: TypeError: accounts.flat is not a function
    at /usr/local/lib/node_modules/mintable/lib/scripts/fetch.js:104:26
    at step (/usr/local/lib/node_modules/mintable/lib/scripts/fetch.js:44:23)
    at Object.next (/usr/local/lib/node_modules/mintable/lib/scripts/fetch.js:25:53)
    at fulfilled (/usr/local/lib/node_modules/mintable/lib/scripts/fetch.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8977) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8977) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
it doesnt fetch anything and nothing is being posted to my google docs

**Comment by gbdavidx** [comment]
I am was able to set it up with my bank, but when i try to add my credit i am getting

[david@unknown5254005cc074 ~]$ mintable account-setup
/usr/local/lib/node_modules/mintable/node_modules/chalk/source/index.js:103
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/mintable/lib/scripts/cli.js:44:13)
    at Module._compile (module.js:570:32)

I am using node version: v.11.15.0

**Comment by a-arbabian** [comment]
@gbdavidx Hey, Im having the same issue. How did you fix this (if you did)? Thanks
