### ISSUE TITLE
Error: Failed to set up Plaid Account(s).

### ISSUE THREAD

**Issue by willie** [kevinschaich/mintable#65]
**Steps to Reproduce:**

1. cloned git repo, switched to 2.0 branch
2. followed instructions to install
3. migrated old config
4. ran `mintable fetch`

**Error:**

```
This script will help you add accounts to Plaid.
2020-06-24T01:33:43.473Z [INFO] Using default configuration file `/Users/willie/mintable.jsonc.`
2020-06-24T01:33:43.473Z [INFO] You can supply either --config-file or --config-variable to specify a different configuration.
2020-06-24T01:33:43.473Z [INFO] Successfully opened configuration file.
2020-06-24T01:33:43.474Z [INFO] Successfully parsed configuration.
File '/Users/willie/src/github.com/kevinschaich/mintable/lib/common/config.js' is a JavaScript file. Did you mean to enable the 'allowJs' option?
2020-06-24T01:33:45.940Z [ERROR] Failed to set up Plaid Account(s).

 TypeError: Cannot read property 'id' of null
    at Ajv._get$Id [as _getId] (/Users/willie/src/github.com/kevinschaich/mintable/node_modules/ajv/lib/ajv.js:392:14)
    at Ajv._addSchema (/Users/willie/src/github.com/kevinschaich/mintable/node_modules/ajv/lib/ajv.js:301:37)
    at Ajv.validate (/Users/willie/src/github.com/kevinschaich/mintable/node_modules/ajv/lib/ajv.js:95:26)
    at Object.exports.validateConfig (/Users/willie/src/github.com/kevinschaich/mintable/lib/common/config.js:98:27)
    at Object.exports.getConfig (/Users/willie/src/github.com/kevinschaich/mintable/lib/common/config.js:110:35)
    at /Users/willie/src/github.com/kevinschaich/mintable/lib/integrations/plaid/add.js:54:35
    at step (/Users/willie/src/github.com/kevinschaich/mintable/lib/integrations/plaid/add.js:33:23)
    at Object.next (/Users/willie/src/github.com/kevinschaich/mintable/lib/integrations/plaid/add.js:14:53)
    at /Users/willie/src/github.com/kevinschaich/mintable/lib/integrations/plaid/add.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/willie/src/github.com/kevinschaich/mintable/lib/integrations/plaid/add.js:4:12)
    at Object.default (/Users/willie/src/github.com/kevinschaich/mintable/lib/integrations/plaid/add.js:47:44)
    at /Users/willie/src/github.com/kevinschaich/mintable/lib/scripts/cli.js:42:82
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/willie/src/github.com/kevinschaich/mintable/lib/scripts/cli.js:42:19)
    at Module._compile (internal/modules/cjs/loader.js:1200:30) 
```

**System Info:**

```
arch: x64
platform: darwin
os: v19.5.0
mintable: v2.0.0
node: v14.4.0
```

**Comment by kevinschaich** [comment]
Thanks @willie. I'm still working out the kinks for the 2.0.0 beta – hang tight for a couple more days and I'll give the all-clear when it's ready for testing.

**Comment by willie** [comment]
Sounds good. Thanks.

**Comment by kevinschaich** [comment]
Hey Willie – this is ready for testing! Would love to have you contribute to the discussion in #55! Thanks.
